// Generated by npm run update-os-icons. Do not edit manually.
import { createAssetRegistryResolver, normalizeRegistryKey } from "src/lib/asset-registry";

export type OperatingSystemId = "ubuntu" | "debian" | "alpine" | "fedora" | "arch" | "raspberry-pi-os" | "truenas" | "proxmox" | "opnsense" | "freebsd" | "linux" | "windows" | "macos" | "docker" | "unknown";

export interface OperatingSystemDefinition {
	id: OperatingSystemId;
	label: string;
	icon: string;
	aliases: readonly string[];
}

export const operatingSystems = [
	{ id: "ubuntu", label: "Ubuntu", icon: "/assets/os/ubuntu.svg", aliases: ["ubuntu-server","ubuntu-lts"] },
	{ id: "debian", label: "Debian", icon: "/assets/os/debian.svg", aliases: ["debian-linux"] },
	{ id: "alpine", label: "Alpine Linux", icon: "/assets/os/alpine.svg", aliases: ["alpine-linux"] },
	{ id: "fedora", label: "Fedora", icon: "/assets/os/fedora.svg", aliases: ["fedora-linux","fedora-server"] },
	{ id: "arch", label: "Arch Linux", icon: "/assets/os/arch.svg", aliases: ["arch-linux","archlinux"] },
	{ id: "raspberry-pi-os", label: "Raspberry Pi OS", icon: "/assets/os/raspberry-pi-os.svg", aliases: ["raspios","raspberry-pi","raspberrypi","raspberry-pi-os"] },
	{ id: "truenas", label: "TrueNAS SCALE", icon: "/assets/os/truenas.svg", aliases: ["truenas","truenas-scale","scale"] },
	{ id: "proxmox", label: "Proxmox VE", icon: "/assets/os/proxmox.svg", aliases: ["proxmox","proxmox-ve","pve"] },
	{ id: "opnsense", label: "OPNsense", icon: "/assets/os/opnsense.svg", aliases: ["opnsense","opn-sense"] },
	{ id: "freebsd", label: "FreeBSD", icon: "/assets/os/freebsd.svg", aliases: ["free-bsd"] },
	{ id: "linux", label: "Linux", icon: "/assets/os/linux.svg", aliases: ["gnu-linux","linux-generic"] },
	{ id: "windows", label: "Windows", icon: "/assets/os/windows.svg", aliases: ["windows-server","windows-10","windows-11","win10","win11"] },
	{ id: "macos", label: "macOS", icon: "/assets/os/macos.svg", aliases: ["mac-os","macos","osx","os-x"] },
	{ id: "docker", label: "Docker", icon: "/assets/os/docker.svg", aliases: ["docker-engine","docker-runtime"] },
	{ id: "unknown", label: "Unknown", icon: "/assets/os/unknown.svg", aliases: ["unknown","other","unspecified"] },
] as const satisfies readonly OperatingSystemDefinition[];

const resolveDefinition = createAssetRegistryResolver(operatingSystems);
const linuxDefinition = operatingSystems.find((item) => item.id === "linux")!;
const unknownDefinition = operatingSystems.find((item) => item.id === "unknown")!;

export function resolveOperatingSystem(osName: string | null | undefined) {
	const resolved = resolveDefinition(osName);
	if (resolved) return resolved;
	const normalized = normalizeRegistryKey(osName ?? "");
	if (/linux|ubuntu|debian|fedora|arch|alpine|raspberry|truenas|proxmox|opnsense|freebsd/.test(normalized)) return linuxDefinition;
	return unknownDefinition;
}

function inlineOsSuffix(osName: string | null | undefined, definition: OperatingSystemDefinition) {
	const source = (osName ?? "").trim();
	if (!source) return "";
	const normalizedSource = normalizeRegistryKey(source);
	const prefixes = [definition.label, definition.id, ...definition.aliases]
		.map((value) => ({ value, normalized: normalizeRegistryKey(value) }))
		.filter(({ normalized }) => normalizedSource === normalized || normalizedSource.startsWith(`${normalized}-`))
		.sort((left, right) => right.normalized.length - left.normalized.length);
	const prefix = prefixes[0]?.value;
	return prefix ? source.slice(prefix.length).trim().replace(/^[-–—:]+\s*/, "") : "";
}

export function formatOperatingSystem(osName: string | null | undefined, version?: string | null) {
	const definition = resolveOperatingSystem(osName);
	const explicitVersion = String(version ?? "").trim();
	const suffix = inlineOsSuffix(osName, definition);
	const details = [suffix, explicitVersion].filter((value, index, values) => value && values.indexOf(value) === index).join(" ");
	return { ...definition, displayLabel: details ? `${definition.label} ${details}` : definition.label };
}
