import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { optimize } from "svgo";

interface OsAssetSource {
	id: string;
	label: string;
	aliases: string[];
	slug?: string;
	color: string;
}

const sources: OsAssetSource[] = [
	{ id: "ubuntu", label: "Ubuntu", aliases: ["ubuntu-server", "ubuntu-lts"], slug: "ubuntu", color: "#E95420" },
	{ id: "debian", label: "Debian", aliases: ["debian-linux"], slug: "debian", color: "#A81D33" },
	{ id: "alpine", label: "Alpine Linux", aliases: ["alpine-linux"], slug: "alpinelinux", color: "#0D597F" },
	{ id: "fedora", label: "Fedora", aliases: ["fedora-linux", "fedora-server"], slug: "fedora", color: "#51A2DA" },
	{ id: "arch", label: "Arch Linux", aliases: ["arch-linux", "archlinux"], slug: "archlinux", color: "#1793D1" },
	{ id: "raspberry-pi-os", label: "Raspberry Pi OS", aliases: ["raspios", "raspberry-pi", "raspberrypi", "raspberry-pi-os"], slug: "raspberrypi", color: "#A22846" },
	{ id: "truenas", label: "TrueNAS SCALE", aliases: ["truenas", "truenas-scale", "scale"], slug: "truenas", color: "#0095D5" },
	{ id: "proxmox", label: "Proxmox VE", aliases: ["proxmox", "proxmox-ve", "pve"], slug: "proxmox", color: "#E57000" },
	{ id: "opnsense", label: "OPNsense", aliases: ["opnsense", "opn-sense"], slug: "opnsense", color: "#D94F00" },
	{ id: "freebsd", label: "FreeBSD", aliases: ["free-bsd"], slug: "freebsd", color: "#AB2B28" },
	{ id: "linux", label: "Linux", aliases: ["gnu-linux", "linux-generic"], slug: "linux", color: "#FCC624" },
	{ id: "windows", label: "Windows", aliases: ["windows-server", "windows-10", "windows-11", "win10", "win11"], color: "#0078D4" },
	{ id: "macos", label: "macOS", aliases: ["mac-os", "macos", "osx", "os-x"], slug: "apple", color: "#A2AAAD" },
	{ id: "docker", label: "Docker", aliases: ["docker-engine", "docker-runtime"], slug: "docker", color: "#2496ED" },
	{ id: "unknown", label: "Unknown", aliases: ["unknown", "other", "unspecified"], color: "#94A3B8" },
];

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const assetDirectory = path.join(projectRoot, "src/assets/os");
const publicAssetDirectory = path.join(projectRoot, "public/assets/os");
const registryPath = path.join(projectRoot, "src/lib/os-registry.ts");
const upstreamRoot = "https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons";

function unknownSvg() {
	return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm0 17.5a1.25 1.25 0 1 1 0-2.5 1.25 1.25 0 0 1 0 2.5Zm1.23-5.34v.59h-2.46v-1.1c0-1.2.55-1.86 1.54-2.5.89-.57 1.38-.94 1.38-1.73 0-.86-.67-1.42-1.7-1.42-1.08 0-1.86.5-2.57 1.42L7.74 7.86C8.8 6.44 10.15 5.7 12.1 5.7c2.47 0 4.18 1.43 4.18 3.55 0 1.75-.92 2.65-2.1 3.4-.7.45-.95.78-.95 1.5Z"/></svg>';
}

function bundledSvg(source: OsAssetSource) {
	if (source.id === "windows") {
		return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M2 4.1 10.7 3v8.35H2V4.1Zm9.7-1.23L22 1.5v9.85H11.7V2.87ZM2 12.35h8.7v8.36L2 19.5v-7.15Zm9.7 0H22v10.15l-10.3-1.45v-8.7Z"/></svg>';
	}
	return unknownSvg();
}

async function loadSource(source: OsAssetSource) {
	if (!source.slug) return bundledSvg(source);
	const response = await fetch(`${upstreamRoot}/${source.slug}.svg`);
	if (!response.ok) throw new Error(`${source.label}: upstream returned ${response.status}`);
	return response.text();
}

function optimizeSvg(svg: string, color: string) {
	const result = optimize(svg, {
		multipass: true,
		plugins: [
			"preset-default",
			"removeDimensions",
			{ name: "removeAttrs", params: { attrs: "(svg|path):(title|aria-label|data-.*)" } },
		],
	});
	return result.data.replace("<svg", `<svg fill="${color}"`);
}

function generateRegistry() {
	const entries = sources.map((source) => {
		return `\t{ id: ${JSON.stringify(source.id)}, label: ${JSON.stringify(source.label)}, icon: "/assets/os/${source.id}.svg", aliases: ${JSON.stringify(source.aliases)} },`;
	}).join("\n");
	return `// Generated by npm run update-os-icons. Do not edit manually.\nimport { createAssetRegistryResolver, normalizeRegistryKey } from "src/lib/asset-registry";\n\nexport type OperatingSystemId = ${sources.map((source) => JSON.stringify(source.id)).join(" | ")};\n\nexport interface OperatingSystemDefinition {\n\tid: OperatingSystemId;\n\tlabel: string;\n\ticon: string;\n\taliases: readonly string[];\n}\n\nexport const operatingSystems = [\n${entries}\n] as const satisfies readonly OperatingSystemDefinition[];\n\nconst resolveDefinition = createAssetRegistryResolver(operatingSystems);\nconst linuxDefinition = operatingSystems.find((item) => item.id === "linux")!;\nconst unknownDefinition = operatingSystems.find((item) => item.id === "unknown")!;\n\nexport function resolveOperatingSystem(osName: string | null | undefined) {\n\tconst resolved = resolveDefinition(osName);\n\tif (resolved) return resolved;\n\tconst normalized = normalizeRegistryKey(osName ?? "");\n\tif (/linux|ubuntu|debian|fedora|arch|alpine|raspberry|truenas|proxmox|opnsense|freebsd/.test(normalized)) return linuxDefinition;\n\treturn unknownDefinition;\n}\n\nfunction inlineOsSuffix(osName: string | null | undefined, definition: OperatingSystemDefinition) {\n\tconst source = (osName ?? "").trim();\n\tif (!source) return "";\n\tconst normalizedSource = normalizeRegistryKey(source);\n\tconst prefixes = [definition.label, definition.id, ...definition.aliases]\n\t\t.map((value) => ({ value, normalized: normalizeRegistryKey(value) }))\n\t\t.filter(({ normalized }) => normalizedSource === normalized || normalizedSource.startsWith(\`${"${normalized}-"}\`))\n\t\t.sort((left, right) => right.normalized.length - left.normalized.length);\n\tconst prefix = prefixes[0]?.value;\n\treturn prefix ? source.slice(prefix.length).trim().replace(/^[-–—:]+\\s*/, "") : "";\n}\n\nexport function formatOperatingSystem(osName: string | null | undefined, version?: string | null) {\n\tconst definition = resolveOperatingSystem(osName);\n\tconst explicitVersion = String(version ?? "").trim();\n\tconst suffix = inlineOsSuffix(osName, definition);\n\tconst details = [suffix, explicitVersion].filter((value, index, values) => value && values.indexOf(value) === index).join(" ");\n\treturn { ...definition, displayLabel: details ? \`${"${definition.label} ${details}"}\` : definition.label };\n}\n`;
}

await mkdir(assetDirectory, { recursive: true });
await mkdir(publicAssetDirectory, { recursive: true });
const updated: string[] = [];
for (const source of sources) {
	const svg = optimizeSvg(await loadSource(source), source.color);
	await writeFile(path.join(assetDirectory, `${source.id}.svg`), `${svg}\n`, "utf8");
	await writeFile(path.join(publicAssetDirectory, `${source.id}.svg`), `${svg}\n`, "utf8");
	updated.push(source.id);
}
await writeFile(registryPath, generateRegistry(), "utf8");
console.log(`Updated ${updated.length} OS assets: ${updated.join(", ")}`);
console.log("Generated src/lib/os-registry.ts");
